# Generated by Django 3.1.4 on 2021-01-12 08:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('emailId', models.CharField(db_column='email_id', max_length=50)),
                ('firstName', models.CharField(db_column='first_name', max_length=50)),
                ('lastName', models.CharField(db_column='last_name', max_length=50)),
                ('password', models.CharField(max_length=20)),
                ('dateOfBirth', models.DateField(db_column='date_of_birth')),
                ('company', models.CharField(max_length=50)),
                ('isAdmin', models.BooleanField(db_column='is_admin', default=False)),
                ('isStaff', models.BooleanField(db_column='is_staff', default=False)),
                ('isActive', models.BooleanField(db_column='is_active', default=False)),
                ('isSuperuser', models.BooleanField(db_column='is_superuser', default=False)),
                ('insertedAt', models.DateTimeField(db_column='inserted_at')),
                ('updatedAt', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
