# Generated by Django 3.1.4 on 2021-01-13 02:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False)),
                ('emailId', models.CharField(db_column='email_id', max_length=50, unique=True)),
                ('firstName', models.CharField(db_column='first_name', max_length=50)),
                ('lastName', models.CharField(db_column='last_name', max_length=50)),
                ('password', models.CharField(max_length=200)),
                ('dateOfBirth', models.DateField(db_column='date_of_birth')),
                ('company', models.CharField(max_length=50)),
                ('isAdmin', models.BooleanField(db_column='is_admin', default=False)),
                ('isStaff', models.BooleanField(db_column='is_staff', default=False)),
                ('isActive', models.BooleanField(db_column='is_active', default=False)),
                ('isSuperuser', models.BooleanField(db_column='is_superuser', default=False)),
                ('insertedAt', models.DateTimeField(db_column='inserted_at')),
                ('updatedAt', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.CharField(editable=False, max_length=100, primary_key=True, serialize=False)),
                ('currency', models.CharField(max_length=10)),
                ('unitAmount', models.IntegerField(db_column='unit_amount', default=0)),
                ('billingScheme', models.CharField(db_column='billing_scheme', default='per_unit', max_length=20)),
                ('interval', models.CharField(default='month', max_length=10)),
                ('intervalCount', models.IntegerField(db_column='interval_count', default=1)),
                ('insertedAt', models.DateTimeField(db_column='inserted_at')),
                ('updatedAt', models.DateTimeField(auto_now=True, db_column='updated_at')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(db_column='product_id', editable=False, max_length=100, primary_key=True, serialize=False)),
                ('productName', models.CharField(db_column='product_name', max_length=50)),
                ('insertedAt', models.DateTimeField(db_column='inserted_at')),
                ('updatedAt', models.DateTimeField(auto_now=True, db_column='updated_at')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.CharField(editable=False, max_length=100, primary_key=True, serialize=False)),
                ('insertedAt', models.DateTimeField(db_column='inserted_at')),
                ('updatedAt', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.price')),
            ],
        ),
        migrations.AddField(
            model_name='price',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.product'),
        ),
    ]
