# Generated by Django 3.1.4 on 2021-01-12 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='emailId',
            field=models.CharField(db_column='email_id', max_length=50, unique=True),
        ),
    ]
