# Generated by Django 3.1.4 on 2021-01-13 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False)),
                ('type', models.CharField(default='card', max_length=50)),
                ('cardNumber', models.CharField(db_column='card_number', max_length=50)),
                ('expiryMonth', models.IntegerField(db_column='expiry_month')),
                ('expiryYear', models.IntegerField(db_column='expiry_year')),
                ('cvv', models.CharField(max_length=3)),
                ('insertedAt', models.DateTimeField(db_column='inserted_at')),
                ('updatedAt', models.DateTimeField(auto_now=True, db_column='updated_at')),
            ],
        ),
        migrations.AddField(
            model_name='manager',
            name='cardDetails',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.paymentmethod'),
        ),
    ]
