# Generated by Django 3.1.4 on 2021-01-12 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20210112_1513'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('productId', models.CharField(db_column='product_id', editable=False, max_length=100, primary_key=True, serialize=False)),
                ('productName', models.CharField(db_column='product_name', max_length=50)),
                ('insertedAt', models.DateTimeField(db_column='inserted_at')),
                ('updatedAt', models.DateTimeField(auto_now=True, db_column='updated_at')),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.CharField(editable=False, max_length=100, primary_key=True, serialize=False)),
                ('currency', models.CharField(max_length=10)),
                ('billingScheme', models.CharField(db_column='billing_scheme', default='per_unit', max_length=20)),
                ('interval', models.CharField(default='month', max_length=10)),
                ('intervalCount', models.IntegerField(db_column='interval_count', default=1)),
                ('insertedAt', models.DateTimeField(db_column='inserted_at')),
                ('updatedAt', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.product')),
            ],
        ),
    ]
