# Generated by Django 3.1.4 on 2021-01-18 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20210113_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='insertedAt',
            field=models.DateTimeField(auto_now=True, db_column='inserted_at'),
        ),
    ]
