# Generated by Django 3.1.4 on 2021-01-18 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20210118_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='isActive',
            field=models.BooleanField(db_column='is_active', default=True),
        ),
        migrations.AlterField(
            model_name='manager',
            name='isAdmin',
            field=models.BooleanField(db_column='is_admin', default=True),
        ),
        migrations.AlterField(
            model_name='manager',
            name='isStaff',
            field=models.BooleanField(db_column='is_staff', default=True),
        ),
        migrations.AlterField(
            model_name='manager',
            name='isSuperuser',
            field=models.BooleanField(db_column='is_superuser', default=True),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='insertedAt',
            field=models.DateTimeField(auto_now=True, db_column='inserted_at'),
        ),
        migrations.AlterField(
            model_name='price',
            name='insertedAt',
            field=models.DateTimeField(auto_now=True, db_column='inserted_at'),
        ),
        migrations.AlterField(
            model_name='product',
            name='insertedAt',
            field=models.DateTimeField(auto_now=True, db_column='inserted_at'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='insertedAt',
            field=models.DateTimeField(auto_now=True, db_column='inserted_at'),
        ),
    ]
