# Generated by Django 3.1.4 on 2021-01-12 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_price_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='productId',
            new_name='id',
        ),
        migrations.AddField(
            model_name='price',
            name='unitAmount',
            field=models.IntegerField(db_column='unit_amount', default=0),
        ),
    ]
